package view;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author luan
 */
public class MainView extends javax.swing.JFrame {

    private Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/icon.png"));
    
    private EmployeeView manageEmployee;
    private StudentView manageStudent;
    private BookView manageBook;
    private LoanView loanBook;
    private FineView fineStudent;
    private SystemView aboutSystem;
    private LicenseView aboutLicense;

    public MainView() {
        initComponents();
        setIconImage(icon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbMenuBar = new javax.swing.JMenuBar();
        mnuManage = new javax.swing.JMenu();
        mniEmpoyee = new javax.swing.JMenuItem();
        mniStudent = new javax.swing.JMenuItem();
        mniBook = new javax.swing.JMenuItem();
        mnuLoan = new javax.swing.JMenu();
        mniLoanBook = new javax.swing.JMenuItem();
        mnuFine = new javax.swing.JMenu();
        mniFineStudent = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mniSystem = new javax.swing.JMenuItem();
        mniLicense = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library");

        mnbMenuBar.setBorder(null);
        mnbMenuBar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        mnuManage.setText("Manage");
        mnuManage.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mnuManage.setPreferredSize(new java.awt.Dimension(75, 23));

        mniEmpoyee.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniEmpoyee.setText("Employee");
        mniEmpoyee.setBorder(null);
        mniEmpoyee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpoyeeActionPerformed(evt);
            }
        });
        mnuManage.add(mniEmpoyee);

        mniStudent.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniStudent.setText("Student");
        mniStudent.setBorder(null);
        mniStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStudentActionPerformed(evt);
            }
        });
        mnuManage.add(mniStudent);

        mniBook.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniBook.setText("Book");
        mniBook.setBorder(null);
        mniBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBookActionPerformed(evt);
            }
        });
        mnuManage.add(mniBook);

        mnbMenuBar.add(mnuManage);

        mnuLoan.setText("Loan");
        mnuLoan.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mnuLoan.setPreferredSize(new java.awt.Dimension(53, 23));

        mniLoanBook.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniLoanBook.setText("Book");
        mniLoanBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoanBookActionPerformed(evt);
            }
        });
        mnuLoan.add(mniLoanBook);

        mnbMenuBar.add(mnuLoan);

        mnuFine.setText("Fine");
        mnuFine.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mnuFine.setPreferredSize(new java.awt.Dimension(49, 23));

        mniFineStudent.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniFineStudent.setText("Student");
        mniFineStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFineStudentActionPerformed(evt);
            }
        });
        mnuFine.add(mniFineStudent);

        mnbMenuBar.add(mnuFine);

        mnuAbout.setText("About");
        mnuAbout.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mnuAbout.setPreferredSize(new java.awt.Dimension(61, 19));

        mniSystem.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniSystem.setText("System");
        mniSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSystemActionPerformed(evt);
            }
        });
        mnuAbout.add(mniSystem);

        mniLicense.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniLicense.setText("License");
        mniLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLicenseActionPerformed(evt);
            }
        });
        mnuAbout.add(mniLicense);

        mnbMenuBar.add(mnuAbout);

        setJMenuBar(mnbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void mniEmpoyeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpoyeeActionPerformed
        manageEmployee = new EmployeeView();
        manageEmployee.setVisible(true);
        manageEmployee.setIconImage(icon);
    }//GEN-LAST:event_mniEmpoyeeActionPerformed

    private void mniStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStudentActionPerformed
        manageStudent = new StudentView();
        manageStudent.setVisible(true);
        manageStudent.setIconImage(icon);
    }//GEN-LAST:event_mniStudentActionPerformed

    private void mniBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBookActionPerformed
        manageBook = new BookView();
        manageBook.setVisible(true);
        manageBook.setIconImage(icon);
    }//GEN-LAST:event_mniBookActionPerformed

    private void mniLoanBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoanBookActionPerformed
        loanBook = new LoanView();
        loanBook.setVisible(true);
        loanBook.setIconImage(icon);
    }//GEN-LAST:event_mniLoanBookActionPerformed

    private void mniFineStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFineStudentActionPerformed
        fineStudent = new FineView();
        fineStudent.setVisible(true);
        fineStudent.setIconImage(icon);
    }//GEN-LAST:event_mniFineStudentActionPerformed

    private void mniSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSystemActionPerformed
        aboutSystem = new SystemView();
        aboutSystem.setVisible(true);
        aboutSystem.setIconImage(icon);
    }//GEN-LAST:event_mniSystemActionPerformed

    private void mniLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLicenseActionPerformed
        aboutLicense = new LicenseView();
        aboutLicense.setVisible(true);
        aboutLicense.setIconImage(icon);
    }//GEN-LAST:event_mniLicenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbMenuBar;
    private javax.swing.JMenuItem mniBook;
    private javax.swing.JMenuItem mniEmpoyee;
    private javax.swing.JMenuItem mniFineStudent;
    private javax.swing.JMenuItem mniLicense;
    private javax.swing.JMenuItem mniLoanBook;
    private javax.swing.JMenuItem mniStudent;
    private javax.swing.JMenuItem mniSystem;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuFine;
    private javax.swing.JMenu mnuLoan;
    private javax.swing.JMenu mnuManage;
    // End of variables declaration//GEN-END:variables
}
