/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.register.EmployeeView;

/**
 *
 * @author luan
 */
public class MainView extends javax.swing.JFrame {

    private EmployeeView registerEmployee;
            
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbMenuBar = new javax.swing.JMenuBar();
        mnuRegister = new javax.swing.JMenu();
        mniEmpoyee = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnbMenuBar.setBorder(null);
        mnbMenuBar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        mnuRegister.setText("Register");
        mnuRegister.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        mniEmpoyee.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mniEmpoyee.setText("Employee");
        mniEmpoyee.setBorder(null);
        mniEmpoyee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpoyeeActionPerformed(evt);
            }
        });
        mnuRegister.add(mniEmpoyee);

        mnbMenuBar.add(mnuRegister);

        mnuEdit.setText("Edit");
        mnuEdit.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        mnbMenuBar.add(mnuEdit);

        setJMenuBar(mnbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniEmpoyeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpoyeeActionPerformed
        registerEmployee = new EmployeeView();
        registerEmployee.setVisible(true);
    }//GEN-LAST:event_mniEmpoyeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbMenuBar;
    private javax.swing.JMenuItem mniEmpoyee;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuRegister;
    // End of variables declaration//GEN-END:variables
}
